apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: memcached-operator-ansible.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: test
  displayName: memcached-operator-ansible
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Memcached Operator Ansible
    url: https://memcached-operator-ansible.domain
  maintainers:
  - email: seansund@us.ibm.com
    name: seansund
  maturity: alpha
  provider:
    name: sms
  version: 0.0.0
